include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # You can enable or disable additional rules here.
    # For example:
    # - camel_case_types
    # - prefer_const_constructors
    # - avoid_print